[general]
email = "your_email@example.com"
# Replace with your email for Streamlit sharing notifications

[server]
headless = true
port = 8501
enableCORS = false
baseUrlPath = "/"
# Set to true if you want to enable CORS

[client]
showErrorDetails = true
[theme]
primaryColor = "#F39C12"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#000000"
font = "sans serif"
